[project]
name = "trading-journal"
version = "0.0.1"
description = "Trading journal automation app."
license = { text = "Proprietary" }
readme = "README.md"
requires-python = "<4.0,>=3.13"

authors = [
    {name = "Mohammed Fareed", email = "mohdf.fareed@icloud.com"}
]

dependencies = [
    "poetry",
    "pydantic",
    "pydantic-settings",
    "dependency-injector",
    "blinker",
    "typer",
    "v20"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pre-commit"
]

[project.scripts]
trading-journal = "app.main:app"

[project.urls]
repository = "https://github.com/mohdfareed/trading-journal"

# MARK: Poetry

[tool.poetry]
packages = [
    { include = "app", from = "." },
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# MARK: Tools

[tool.mypy]
strict = true
enable_incomplete_feature = ["NewGenericSyntax"]
